steps:
- name: gcr.io/moonrhythm-containers/golang:1.15.0-alpine3.12
  args: [go, build, -o, httpproxy, -ldflags, -w -s, main.go]
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=1
  - GOPROXY=https://proxy.golang.org
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/httpproxy:master, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/httpproxy:master, gcr.io/$PROJECT_ID/httpproxy:$COMMIT_SHA]

images:
- gcr.io/$PROJECT_ID/httpproxy:master
- gcr.io/$PROJECT_ID/httpproxy:$COMMIT_SHA
