steps:
- name: golang:1.18.3
  args: [go, build, -o, httpproxy, -ldflags, -w -s, main.go]
  env:
  - CGO_ENABLED=0
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/httpproxy:master, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/httpproxy:master, gcr.io/$PROJECT_ID/httpproxy:$COMMIT_SHA]

images:
- gcr.io/$PROJECT_ID/httpproxy:master
- gcr.io/$PROJECT_ID/httpproxy:$COMMIT_SHA
