steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/httpproxy, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/httpproxy, gcr.io/$PROJECT_ID/httpproxy:$TAG_NAME]

images:
- gcr.io/$PROJECT_ID/httpproxy
- gcr.io/$PROJECT_ID/httpproxy:$TAG_NAME
