steps:
- name: gcr.io/moonrhythm-containers/golang:1.12.7-alpine3.10
  args: [go, build, -o, httpproxy, -ldflags, -w -s, main.go]
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=1
  - GOPROXY=https://proxy.golang.org
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/httpproxy, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/httpproxy, gcr.io/$PROJECT_ID/httpproxy:$TAG_NAME]

images:
- gcr.io/$PROJECT_ID/httpproxy
- gcr.io/$PROJECT_ID/httpproxy:$TAG_NAME
